### ISSUE TITLE
Robot stops at poses where it is to stretched  

### ISSUE THREAD

**Issue by joao-pm-santos96** [joao-pm-santos96/SmObEx#21]
Already tried giving tighter bound limits

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 ,

did the tightening of the robot's joint limits worked? Did you see the problem again?

**Comment by joao-pm-santos96** [comment]
Hello @miguelriemoliveira ,

no it didn't, I happened to me once or twice on tuesday.

**Comment by joao-pm-santos96** [comment]
[ERROR] [1556784559.089881692]: Socket sendBytes failed, rc: -1. Error: 'Connection reset by peer' (errno: 104)
[ERROR] [1556784559.100206879]: Failed to connect to server, rc: -1. Error: 'Transport endpoint is already connected' (errno: 106)
[ERROR] [1556784559.355468608]: Failed to connect to server, rc: -1. Error: 'Transport endpoint is already connected' (errno: 106)
[ERROR] [1556784559.610696564]: Failed to connect to server, rc: -1. Error: 'Transport endpoint is already connected' (errno: 106)
[ERROR] [1556784559.866021131]: Failed to connect to server, rc: -1. Error: 'Transport endpoint is already connected' (errno: 106)
[ERROR] [1556784560.121396369]: Failed to connect to server, rc: -1. Error: 'Transport endpoint is already connected' (errno: 106)
[ERROR] [1556784560.371564861]: Timeout connecting to robot controller.  Send new motion command to retry.

**Comment by joao-pm-santos96** [comment]
Just found out something that must be important!! 

Let's say that the exploration node is running and the robot stops at one of these points. What I normally do to start again is, using MoveIt!, take it to a safe location ans that works just fine, UNLESS I set true tha option "Use Cartesian Path" in Rviz/MoveIt!. Setting it to true gives the exact same error even before it starts moving. So it must be it... 

The question is, nowhere is the code it's used cartesian path... will need to investigate but it's a step forward.

**Comment by miguelriemoliveira** [comment]
But is it less often than before? If so you can increase the delta just to
see what happens...
*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by joao-pm-santos96** [comment]
I already did that it's not the problem, please see my previous comment 

> Just found out something that must be important!!
> 
> Let's say that the exploration node is running and the robot stops at one of these points. What I normally do to start again is, using MoveIt!, take it to a safe location ans that works just fine, UNLESS I set true tha option "Use Cartesian Path" in Rviz/MoveIt!. Setting it to true gives the exact same error even before it starts moving. So it must be it...
> 
> The question is, nowhere is the code it's used cartesian path... will need to investigate but it's a step forward.

**Comment by joao-pm-santos96** [comment]
Seams to be an [Elbow singularity](https://blog.robotiq.com/why-singularities-can-ruin-your-day)

**Comment by joao-pm-santos96** [comment]
The working sphere didn't solve it

**Comment by joao-pm-santos96** [comment]
Generated IKFAST plugin for the specific robot, using [this tutorial](https://acutronicrobotics.com/docs/products/robots/mara/moveit2/tutorials/ros/ikfast). Add to run part of it on Ubuntu 16.04 in a VM, thought... tomorrow will test to see if improves anything

**Comment by miguelriemoliveira** [comment]
Hope it works. ..

A Dom, 5/05/2019, 20:12, João Santos <notifications@github.com> escreveu:

**Comment by joao-pm-santos96** [comment]
The OpenRAVE (and includes IKFAST) worked out but it still stops in the same kind of poses... tried to use the most recent version of OpenRAVE in the master branch but doesn't even compile because "error: no matching function for call to ‘min(long unsigned int&, unsigned int&)"... working on it but it's taking a lot of time this issue

**Comment by joao-pm-santos96** [comment]
I now have a python script that consistently passes in a problematic point

![TP](https://user-images.githubusercontent.com/47630528/57874790-4f2e8b80-7809-11e9-9716-36ee1922258a.JPG)

**Comment by joao-pm-santos96** [comment]
The issue seams to be when the elbow wants to change its redundancy, not sure of this just a visual ideia

**Comment by miguelriemoliveira** [comment]
a photo of the robot when the problem occurs could be helpful.


*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by joao-pm-santos96** [comment]
The /joint_states:

```bash
header: 
  seq: 4513
  stamp: 
    secs: 1558098922
    nsecs: 156394777
  frame_id: ''
name: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
position: [1.5252118110656738, 1.3908336162567139, 1.3533990681171417, 1.9825726747512817, -2.0937976837158203, 1.3225916624069214]
velocity: []
effort: []
---
```

The photos:

![Photo 17-05-2019, 14 15 44](https://user-images.githubusercontent.com/47630528/57931608-c5d29400-78b0-11e9-8d95-2399a62d07ab.jpg)
![Photo 17-05-2019, 14 16 02](https://user-images.githubusercontent.com/47630528/57931609-c66b2a80-78b0-11e9-80fe-eac8fa779958.jpg)
![Photo 17-05-2019, 14 16 02 (1)](https://user-images.githubusercontent.com/47630528/57931610-c66b2a80-78b0-11e9-9cb4-b09a7086b255.jpg)

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 ,

nice to see you are writing you thesis :-).

Please post the joint limits that were being used, as defined by the xacro file?

**Comment by joao-pm-santos96** [comment]
Well @miguelriemoliveira I would feel bad if I had to keep you waiting for those the beautiful photos!!

The xacro values are overwritten by joint_limits.yaml which as the following content: 

```yaml
# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.4906
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: deg(-170.0)
    max_position: deg(170.0)
  joint_2:
    has_velocity_limits: true
    max_velocity: 3.4906
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: deg(-90.0)
    max_position: deg(160.0)
  joint_3:
    has_velocity_limits: true
    max_velocity: 4.5378
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: deg(-140.0)
    max_position: deg(170.0)
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: deg(-190.0)
    max_position: deg(190.0)
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: deg(-140.0)
    max_position: deg(140.0)
  joint_6:
    has_velocity_limits: true
    max_velocity: 12.5663
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: deg(-360.0)
    max_position: deg(360.0)
```

those values are the ones defined in the Teach Pendant
